### ISSUE TITLE
Papyrus Compare NPE when showing differences of certain diagrams.

### ISSUE THREAD

**Issue by eposse** [ZeligsoftDev/CX4CBDDS#171] opened 2020-07-29 21:16 UTC
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

An NPE that is reported in a pop-up is thrown when showing certain diagrams while doing a model-comparison.

This has been observed when comparing modifications to the BasicPubSub_new model from the git repo examples. One version of the model added a new publisher and another version in a parallel branch added a couple of subscribers. 

The error log is attached.

[exception.log](https://github.com/ZeligsoftDev/CX4CBDDS/files/4997509/exception.log)

**Comment by eposse** [comment] 2021-03-04 23:08
@j26151 I've been getting an NPE which is the same as the one you reported in Issue #170, but I'm not sure if this is the only one. When I reported this issue, it was an NPE thrown when showing diagrams in the comparison, but the NPE in some other case, e.g. when resolving a merge.

Do you have an idea of when you get the NPE? Also, can you check if it's the same? For reference, this is the relevant part of the exception trace:

```
!ENTRY org.eclipse.jface 4 2 2021-03-02 10:59:47.414
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.emf.edit.ui.provider.AdapterFactoryContentProvider.getPropertySource(AdapterFactoryContentProvider.java:244)
	at org.eclipse.ui.views.properties.PropertySheetEntry.getPropertySource(PropertySheetEntry.java:452)
	at org.eclipse.ui.views.properties.PropertySheetEntry.setValues(PropertySheetEntry.java:721)
	at org.eclipse.emf.edit.ui.view.ExtendedPropertySheetPage$ExtendedPropertySheetEntry.setValues(ExtendedPropertySheetPage.java:942)
	at org.eclipse.ui.views.properties.PropertySheetViewer.setInput(PropertySheetViewer.java:979)
	at org.eclipse.ui.views.properties.PropertySheetPage.selectionChanged(PropertySheetPage.java:556)
	at org.eclipse.emf.edit.ui.view.ExtendedPropertySheetPage.selectionChanged(ExtendedPropertySheetPage.java:553)
	at org.eclipse.emf.compare.ide.ui.internal.contentmergeviewer.EMFCompareContentMergeViewer.updatePropertiesView(EMFCompareContentMergeViewer.java:764)
	at org.eclipse.emf.compare.ide.ui.internal.contentmergeviewer.EMFCompareContentMergeViewer.synchronizeSelection(EMFCompareContentMergeViewer.java:712)
	at org.eclipse.emf.compare.ide.ui.internal.contentmergeviewer.EMFCompareContentMergeViewer.selectionChanged(EMFCompareContentMergeViewer.java:704)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
...
```

**Comment by j26151** [comment] 2021-03-05 16:12
I want to preface this by stating that I have only gotten the NPE by following the unapproved workflow. If I ever try to merge the models that I work with in eclipse, the result is always an automatic merge, which doesn't result in any NPEs.

When following the unapproved workflow, selecting the conflicted model in eclipse, in the git staging view, will randomly, about 50% of the time, show 4 NPEs.

**Comment by eposse** [comment] 2021-03-05 16:47
I am getting an NPE when working exclusively with EGit, but not always. I'm trying to figure out the conditions for it to happen. This seems to happen when displaying the "merge viewer". I'm debugging it, but I don't understand yet why it happens. I'll keep you posted.

If you see NPEs with a different trace from the above, let me know. I don't know yet if it is only this one.

**Comment by ysroh** [comment] 2021-05-03 15:30
@j26151 Let me know if we can close this issue. Ernesto tested with latest Papyrus branch and was not able to reproduce.

**Comment by ysroh** [comment] 2021-05-05 14:58
@eposse Can we close this issue?

**Comment by J17359** [comment] 2021-05-06 10:47
@ysroh - Let's close this issue. We had so many different NPE tickets spawn in GitHub while Ernesto was working the model merging stuff that I can't keep them straight any longer. If Ernesto cannot reproduce, I'm fine with marking this closed and writing a new ticket in the future if we find something we can reliable reproduce. Thanks!

**Comment by ysroh** [comment] 2021-05-06 14:04
Closing this issue. We can raise a new ticket if any problem arises with compare merge.

**Closed by ysroh** 2021-05-06 14:04 UTC
Labels: Priority: Major, bug
