### ISSUE TITLE
Incorrect Referenced Models paths

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#416] opened 2022-08-02 16:58 UTC
# **Issue and tracking information**
We are seeing an issue where pathmap paths are replacing actual model resource paths in the SDK GUI upon starting up a workspace and first opening a model. After closing the model and then reopening it the problem is solved. However, if any changes are made to the model and it is saved, this pathmap issue is retained.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment] 2022-08-02 17:20
Do you see this issue for models that are left open from the previous workspace session?

**Comment by ysroh** [comment] 2022-08-16 15:38
I reproduced this problem. The dynamic pathmap works by manipulating the EMF URI mappings feature, which is all about mapping directories. Unfortunately, Papyrus or possibly EMF does not seem to have deterministic result loading references to another model in the same folder if it is path mapped. So I recommend users put the path-mapped model in a separate folder rather than mixing it with other models, as it will confuse the system.
I am not sure if there is any other solution to this problem.
This issue is a pitfall of using the dynamic pathmap and one of the limitations that we might have to live with.
One thing I could do is to warn or disallow users to create mapping if the folder contains other models.
Do you think this would be the acceptable solution?

**Comment by j26151** [comment] 2022-08-16 15:41
I don't think this is a solution that will work for our users. We have project that contain a set of models, both ICMs and non-ICMs. It would require re-organizing of staple repos that users are used to seeing.

The only time we see this problem is on startup of eclipse. After opening/closing a model, it appears to resolve it self. Is there no way to cause eclipse to automatically "re-figure things out" before the user starts doing anything with models?

**Comment by ysroh** [comment] 2022-08-16 15:48
Let me investigate more to see if we can do something about this.

**Comment by j26151** [comment] 2022-08-16 15:51
Thank you. We are open to suggestions, I just don't know that changing our folder structure to have different folders for each ICM is one that our program and product management will go for

**Comment by ysroh** [comment] 2022-08-17 20:04
Can you please test the "papyrus_pathmap" branch? This fix contains quite a bit of code refactoring to make this work. Please try dynamic pathmap use cases in general, not limited to the issue described in this ticket.

**Comment by j26151** [comment] 2022-08-19 17:25
Initial testing shows that the original bug is fixed, but now some of our production code that has multiple dynamic pathmap references in a hierarchical structure is not working. I do not have a reproducer that we can share at the moment, it will take some time to create this, but from what I can tell, something is broken by this change.

**Comment by ysroh** [comment] 2022-08-19 17:35
I think the reason is that saved mapping is lost since the mapping registry moved to a different plugin. I might have to create a migration for this. Please verify that everything works once you set the mapping again.

**Comment by ysroh** [comment] 2022-08-19 18:00
I will make some changes and let you know when it is ready.

**Comment by ysroh** [comment] 2022-08-19 18:44
I found out that the mapping selection wasn't saved properly, and it is fixed now. Hopefully, that's the cause of the problem you are seeing. Let me know if you still have an issue with the latest change, and the reproducer would be helpful.

**Comment by ysroh** [comment] 2022-08-19 19:03
Here is the pull request: https://github.com/ZeligsoftDev/CX4CBDDS/pull/422

**Comment by j26151** [comment] 2022-08-20 14:01
From what I can tell, everything seems to be working correctly right now. I did have a few errors when opening models that were complaining about missing references when using an existing workspace. After refreshing a few times, opening the models a few times and getting to a state where everything was happy, I couldn't reproduce it again. I will chalk those errors up to just being a weird workspace issue. I think we are good with this fix

**Comment by ysroh** [comment] 2022-08-22 12:19
Thanks. The pull request is merged.

**Comment by ysroh** [comment] 2022-08-23 14:20
Closing this ticket

**Closed by ysroh** 2022-08-23 14:20 UTC
Labels: bug, NGC: Approved To Work
