### ISSUE TITLE
Improvements for Pathmap Conflicts

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#409] opened 2022-07-12 12:11 UTC
# **Issue and tracking information**
We would like the following added to the pathmap conflict dialog:

1. One dialog for all pathmap conflicts
2. In the dialog, a radio selection for each pathmap conflict that allows us to select which one we want to use
3. A checkbox for each conflict that says something along the lines of "If there are no changes to the available pathmaps for this conflict, do not warn be about them again"
4. A link in the bottom of the dialog to the Windows>Preferences>CX>Modeling>URI Mappings that users can click to open up the URI preferences section to see all active pathmaps.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment] 2022-07-29 16:43
Is it possible to test this feature using the "papyrus_bugfix" branch?

This is the dialog for conflict pathmaps and users will be able to suppress future warnings as long as there are no new mappings introduced for the same pathmap.
![image](https://user-images.githubusercontent.com/896503/181803899-eb554260-c732-470c-a5dd-ef0f318ea5ba.png)

Users will be able to choose the mapping from the URI mappings preference page.
![image](https://user-images.githubusercontent.com/896503/181805435-cf182d98-6b08-4502-b2cf-7de41912188c.png)

Let me know if you have any questions or comments.

**Comment by j26151** [comment] 2022-07-29 16:52
A few things:

1. I am all for testing tickets using alternative "bug fix" branches before pushing in larger tickets.
2. I would like to see what happens when we see multiple pathmap conflicts. One of the things we want to see is a single dialog that lists all pathmap conflicts when they are recognized. That way the user doesn't have to keep making selections and then new dialogs keep popping up for other conflicts.
3. In your example above, it seems like the only solution is to accept the mapping change that you are suggesting. What if in the dialog above I didn't want "test2" and I still wanted the first one? I know I can go to the URI Mappings preference, but it would be preferred to also select which pathmap I want in the warning dialog itself.

**Comment by ysroh** [comment] 2022-07-29 17:24
Thanks for the input.
Please see the comments in-line.
> A few things:
> 
> 1. I am all for testing tickets using alternative "bug fix" branches before pushing in larger tickets.
ys] ok thanks
> 2. I would like to see what happens when we see multiple pathmap conflicts. One of the things we want to see is a single dialog that lists all pathmap conflicts when they are recognized. That way the user doesn't have to keep making selections and then new dialogs keep popping up for other conflicts.
ys] See the answer to question 3.
> 3. In your example above, it seems like the only solution is to accept the mapping change that you are suggesting. What if in the dialog above I didn't want "test2" and I still wanted the first one? I know I can go to the URI Mappings preference, but it would be preferred to also select which pathmap I want in the warning dialog itself.

ys] I will add the mapping selection combo box right in the warning dialog for the pathmap so users can select the mapping when they appear.

I will make this change and let you know when it is ready.

**Comment by j26151** [comment] 2022-07-29 17:41
One quick comment to. When I say "multiple pathmap conflicts", I mean for literally different pathmaps altogether. So, for example, we might have a model "ModelA.uml" with a pathmap "MYPATHMAP". Then we have a totally different model "ModelB.uml" with a different pathmap "DIFFERENTPATHMAP". If somehow I have conflicts for both of those, currently we get a dialog for the conflict for ModelA, and then a seperate dialog for the conflict for ModelB

**Comment by ysroh** [comment] 2022-07-29 18:13
The changes are coming continuously from the Eclipse workspace change listener so we do not really know when to open the dialog for all warnings. You may get several events coming in separately or together containing multiple pathmap changes.

**Comment by ysroh** [comment] 2022-07-29 18:17
We can do the one dialog IF the mapping is done once at the start up and triggered by the "remap" button any other time. This means that no automatic pathmap activation when you drag or import a new project into the workspace.

**Comment by ysroh** [comment] 2022-07-29 18:30
I will experiment with something so that at least one dialog is open for all changes during the initial start-up, but might not guarantee this when multiple projects are brought into the workspace. I will let you know when I have something to show.

**Comment by ysroh** [comment] 2022-07-29 19:38
I can make one dialog but the catch is that I cannot know which pathmaps are once that are newly added so I have to show all pathmaps that have multiple mappings in the dialog. Is this acceptable??

**Comment by j26151** [comment] 2022-08-01 10:45
That looks better. My next question would be what the pathmap the bottom check box is referring to? My guess is pathmap://PATHMAP222, but it might be nice if the table had a new column with checkboxes or true/false for whether or not to suppress warnings

**Comment by ysroh** [comment] 2022-08-01 12:40
I am making changes so that only new conflicts that are not suppressed will show up on the dialog. There are quite a bit of code changes since we are now keeping multiple path mappings in order to support changes between multiple mappings. I will let you know when things are ready so you can test them.

**Comment by ysroh** [comment] 2022-08-04 15:48
Here is the pull request: https://github.com/ZeligsoftDev/CX4CBDDS/pull/418
A new column is added for the suppressed warning state.

**Comment by ysroh** [comment] 2022-08-08 14:10
Thanks. I will take a look at the issue.

**Comment by ysroh** [comment] 2022-08-08 14:31
I did not reproduce the same issue you described. I think it might depend on how those projects are imported. I imported all of them together via File->Import-> Import existing project and selected the root folder that contains all sub folders. 

![image](https://user-images.githubusercontent.com/896503/183442277-1ce07370-e03a-4ef2-bf5f-327517aa48a2.png)

Can you please describe steps to import those copied projects into workspace?

**Comment by j26151** [comment] 2022-08-08 14:32
Import the Original non-numbered projects first. So ProjectA, ProjectB, and ProjectC. Then, import the other 9 after that.

**Comment by ysroh** [comment] 2022-08-08 14:36
Ok. I was able to reproduce it.

**Comment by ysroh** [comment] 2022-08-08 15:17
@j26151 Can you please check to see if the issue is fixed?

**Comment by j26151** [comment] 2022-08-08 18:18
Everything else looks good to me. One last thing however. When the current mapped pathmap is removed, it looks like CX just picks what dynamic pathmap it will use instead. Can we instead show the same dialog with CXs suggestion as the current value? This way the user could select something else

**Comment by ysroh** [comment] 2022-08-08 18:45
Absolutely, I will work on it and let you know.

**Comment by ysroh** [comment] 2022-08-08 20:47
Done. I will merge the pull request after code review if no other issues are found.

**Comment by j26151** [comment] 2022-08-10 12:26
I do understand the need for the right dialog now after actually reading it. Although we would want those consolidated as well. So maybe the above can become 2 dialogs instead of 4?

**Comment by ysroh** [comment] 2022-08-10 13:01
Yes. I didn't think of that case. I will look into it and let you know.

**Comment by ysroh** [comment] 2022-08-11 13:52
I've started the pull request for this fix. https://github.com/ZeligsoftDev/CX4CBDDS/pull/421
Can you verify that the fix works on your side?

**Comment by j26151** [comment] 2022-08-11 17:56
I was seeing all kinds of different behavior. The first time I tried to import a few more models with conflicting pathmaps, my eclipse hung for a few minutes. The second time, when I tried to remove some projects that were the current pathmaps, I still got all of the disparate dialogs . Also, I got this NPE:

![image](https://user-images.githubusercontent.com/49879646/184204889-c85cd424-be1f-4429-be7d-206adeac1897.png)

**Comment by ysroh** [comment] 2022-08-12 03:28
I've made some changes to make it more robust. 
You will notice some delays when you import or remove dynamic models to consolidate all possible event sequences. 
Can you please verify this?

**Comment by ysroh** [comment] 2022-08-12 15:12
I think things are working much better now :)

**Comment by j26151** [comment] 2022-08-15 12:21
When I delete 2+ projects each containing a pathmapped model in one delete operation, I still receive multiple dialogs for the pathmaps: 
![image](https://user-images.githubusercontent.com/49879646/184634158-ec5e9bed-199d-46cd-bcb8-49908e399a82.png)

**Comment by ysroh** [comment] 2022-08-15 14:13
The only way to consolidate dialogs is to wait for the next event. What is the optimal delay to wait for the next event is unknown. If you wait longer then you are guaranteed to get one dialog but the Eclipse will freeze for a longer period. If you set a shorter delay then you might get multiple dialogs if an event process time takes longer than the delay period. 

I added new field in the URI mappings preference page to set the delay time to consolidate dialogs so you can set the delay yourself. Can you try different delay values to see what works best for you? I can set that delay value to be the default. 

There will be no perfect value for this so please let me know the value that works best for the average use cases rather than the edge case.

**Comment by j26151** [comment] 2022-08-16 11:52
This looks great to me.  I think we should set the value to  1 second for now. 1 second worked for me. If our users have issues with 1 second we can revisit it later. The last fix I would ask for is that the 
![image](https://user-images.githubusercontent.com/49879646/184873056-363ce813-dade-4358-b9af-f582f7e8e63e.png)
"Open URI Mappings preference page for all pathmap list" changed to "Open URI Mappings preference page for full pathmap list"

**Comment by ysroh** [comment] 2022-08-16 13:44
All done and merged.

**Comment by j26151** [comment] 2022-08-19 15:11
I have verified this on our end. Thank you

**Comment by ysroh** [comment] 2022-08-19 15:38
Thanks

**Closed by ysroh** 2022-08-19 15:38 UTC
Labels: enhancement, NGC: Approved To Work
