### ISSUE TITLE
Default "unbounded" sequences to a value (100) in IDL to match what RTI's IDL compiler does

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#234] opened 2021-05-06 10:49 UTC
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
RTI's IDL compiler defaults all unbounded sequences to 100. This means that all unbounded sequences in SNA, when using RTI, are really sequences bounded to 100. This should be reflected in CX to make it easier to understand by developers and to have the IDL just reflect this hidden default.

**Comment by J17359** [comment] 2021-05-06 10:50
Please work this before the PATHMAP safeguard ticket (#191 ) if possible.

**Comment by ysroh** [comment] 2021-05-06 11:50
I will work on this first. To be clear, we need to treat unbounded sequences as if they have 100 as value when generating descriptor file?

**Comment by ysroh** [comment] 2021-05-06 12:11
Actually. I will set the default value of sequence bound to 100 when it is created if that’s ok.

**Comment by j26151** [comment] 2021-05-06 12:15
@ysroh No, we don't want the default value set to 100. We want the value of "Unlimited" or "infinited" or whatever it is to default to 100 (more specifically, a configurable value) when IDL is generated. Descriptor files (CDP and CDD) do not contain or care about unbounded sequences.We are only concerned with IDL files.

**Comment by ysroh** [comment] 2021-05-06 14:02
@J17359 Got it. I have one more question. If unlimited translates to 100 then what about any value that is greater than 100 set by user?

**Comment by j26151** [comment] 2021-05-06 14:07
@ysroh Two things:

- We want unlimited to translate to 100 by default, but we want this value to be modifiable. In otherwords, a preference setting that is set to 100, but could be changed. When the user generates IDL, whatever value is in that preference setting is what is used to set sequence bounds. Additionally, this preference should allow a user to set the value to -1, or unlimited, in which case the sequences generated in the IDL would truly be unbounded. This is the current behavior, and while we do not want it to be the default, we should still provide it.
- Values over 100 are fine. The issue that we are trying to resolve is the one where RTI sets all unbounded sequences to 100 by default. This causes issues when trading IDL between developers who may be using different DDS vendors. If the IDL specifies all sequence bounds, then the IDL would create the same DDS types in any DDS impelementation (theoretically)

**Comment by ysroh** [comment] 2021-05-06 14:10
@J17359 Thanks for the clarification. I will let you know when I have the fix ready. Thanks.

**Comment by ysroh** [comment] 2021-05-10 12:07
Fix merged to papyrus branch.

**Comment by j26151** [comment] 2021-05-12 14:54
@ysroh I was able to test out your change today. I think there is a small miscommunication. We do not want to default a "null" bounds to the values specified in the preference page. This would be bad as it takes information out of the model and hides it in the generation step, which can make understanding the interface difficult. 
What we would like is the value "CCM_DDS::UNLIMITED" modified to take the value specified in the preference page when generated to IDL. Either that, or a new bounds value, say "RTI_UNBOUNDED", that can be filled in with the value in that preference page. The issue is that when "CCM_DDS::UNLIMITED" is placed in the IDL file, RTI assumes 100 (unless the IDL is generated differently).

**Comment by ysroh** [comment] 2021-05-12 15:13
@j26151 I see. I will update the code to translate CCM_DDS::UNLIMITED to the value specified in the preference page. Thanks

**Comment by ysroh** [comment] 2021-05-12 16:23
@j26151 
Here is the snapshot of the preference page.
![image](https://user-images.githubusercontent.com/896503/118009801-6501b900-b31c-11eb-8afb-92ccdef1694f.png)

The CCM_DDS::UNLIMITED will be translated to the value specified but if this field is empty or -1 then "CCM_DDS::UNLIMITED" will be the sequence bound like before.

Let me know if have any comments on this before I make final change.

Thanks.

**Comment by j26151** [comment] 2021-05-12 16:25
That looks good to me.

**Comment by j26151** [comment] 2021-05-12 16:37
Actually, can you give me a little bit of time to verify with some of our applications before making this change

**Comment by j26151** [comment] 2021-05-12 17:44
Alright, so I think that we want to do what you have above (where CCM_DDS::UNLIMITED will be translated to the value), the only other fix that I want to state is that if the value is -1 or the field is empty, then the sequences generated should be

typedef sequence <long> testSeq;

and not

#include "CCM_DCPS.idl"
....
typedef sequence <long, CCM_DDS::UNLIMITED> testSeq;

CCM_DDS::UNLIMITED is defined in a file in axcioma (dds4ccm_base.idl), but as far as I can tell, it is not meant for us to use or include. Also, the include CCM_DCPS.idl does not exist in axcioma.

**Comment by ysroh** [comment] 2021-05-12 17:52
@j26151 Thanks. I will make that change.

**Comment by ysroh** [comment] 2021-05-14 01:52
This should be fixed now.

**Comment by j26151** [comment] 2021-05-17 12:55
I have verified this on our end, thank you. You can close this issue whenever you want.

**Closed** 2021-05-17 14:18 UTC
Labels: NGC: Approved To Work, enhancement
