### ISSUE TITLE
Minimize usage of randomly generated UUIDs in deployment artifacts

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#408] opened 2022-07-12 12:09 UTC
# **Issue and tracking information**
The usage of randomly generated UUIDs obfuscates the majority of functional changes in  CDP and CDD files, and reduces usability of pull requesting tools.  This confuses a majority of developers in both deployment and new updates.  Remove the usage of UUIDs and come up with a static way to set them possibly using a hierarchical naming approach.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by eposse** [comment] 2022-11-04 21:12
I've opened PR #438. I think it addresses this issue. UUIDs are replaced with CORBA scoped names with two exceptions:

1) The top-level UUID field of the CDP or CDD (since it is a UUID field after all)
2) The id of connectors, since the connector is identified by the source, the target, the data space and the node. In this case, for the is we use the same format at the name: <_dataspace-qual-name_>-to-<_source-name_>@<_node-name_>.<_target-name_>.

A couple of things to note here about the naming. The "-to-" appears between the dataspace name and the source, as this was the same format that existed for names. I personally find it confusing, and I would put it between the source and the target, something like <_dataspace-qual-name_>:<_source-name_>-to-<_target-name_>@<_node-name_>. Would this be preferable (both for the id and the name fields)?

Also, we are using dots (.) as separators. The names replace them with underscores, but that leads to ambiguous names and ids, since the non-qualified names may already include underscores. Let us know if using dots as delimiters is ok with you. And also characters such as '-' and '@' for connector ids.

**Comment by j26151** [comment] 2022-11-07 12:17
Can you attach an example CDP Generated in this new format? Possibly one for BPS. 

> A couple of things to note here about the naming. The "-to-" appears between the dataspace name and the source, as this was the same format that existed for names. I personally find it confusing, and I would put it between the source and the target, something like <dataspace-qual-name>:<source-name>-to-<target-name>@<node-name>. Would this be preferable (both for the id and the name fields)?

Can you attach the same CDP generated with your suggestion here as well?

**Comment by eposse** [comment] 2022-11-07 16:39
I'm attaching the original CDP for BasicPubSub (for comparison), and two more: BasicPubSub_v1.cdp which has the updated ids but keeps the format for connectors, and BasicPubSub_v2.cdp with the proposed change.

Let me know what you prefer.

[BasicPubSub_original.cdp.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/9953650/BasicPubSub_original.cdp.txt)
[BasicPubSub_v1.cdp.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/9953651/BasicPubSub_v1.cdp.txt)
[BasicPubSub_v2.cdp.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/9953652/BasicPubSub_v2.cdp.txt)

**Comment by j26151** [comment] 2022-11-11 15:48
Thank you for the examples. I think I prefer the way that it is already and not the proposed change. The format of <conn>-to-<component>@<node>-<process> makes more sense to me than <conn>:<component>-to-<process>@<node>

One thing I am noticing here that might be an edge case that we never see is if we ever had 2 ports on the same component, connected to the same dataspace conn. I can't think of real use-cases for this, however, if this would happen the ID would be the same for both since the ID doesn't contain any information about the port that the "conn" is connected to. Could we add that in to be <conn>-to-<component>::<port>@<node>-<process>?

**Comment by eposse** [comment] 2022-11-11 20:26
Yes we can add that.

**Comment by eposse** [comment] 2022-11-14 22:47
I've pushed the update and I'm attaching a new model that tests the scenario you suggested, including the case where the parts are nested inside some assembly. See the "ExtraComplexApp" example in the attached model. The zip file also includes the generated descriptors, both the original (before the change) and the newly generated ones.

Let me know if this is ok with you and if we can merge it and close it.

[axPubSub.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/10007639/axPubSub.zip)

**Comment by j26151** [comment] 2022-11-16 11:59
This is looking better, but I still have a question regarding the format of connection IDs. What I am seeing is that the component name was removed and replaced by the port with a "msgIn" or "msgOut" added. I see the following:
`<conn>-to-<port>::msg[In, Out]@<node>.<process>`
We would like to show that that the connector <conn> is connecting to a given port on a component. E.g. `<component>::<port>`. I am not sure where the "msgIn" or "msgOut" comes from but we don't really need that information as we already have the port name which is usually, <something>Pub or <something>Sub
`<conn>-to-<component>::<port>@<node>.<process>`

**Comment by eposse** [comment] 2022-11-16 19:24
Sure. A build is available [here](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/3465775641).

**Comment by j26151** [comment] 2022-11-18 18:05
Thanks, I was able to try this out and not-surprisingly, AXCIOMA didn't like the new CDP. It looks like ':' and '@' are not well received. I looked it up, and the regex here: http://books.xmlschemata.org/relaxng/ch19-77215.html is all that is allowed in the xmi:idref field.

So, if we replace all "@" characters with "-at-" and all "::" with "_" it allows us to deploy.

**Comment by eposse** [comment] 2022-11-18 19:03
I've pushed the changes. The build should be ready in about 20min to 30min. 

Just to confirm, AXCIOMA doesn't mind the '.' and '-' characters in the id?

**Comment by j26151** [comment] 2022-11-19 12:52
As far as I can tell, anything here [-._:A-Za-z0-9] should be allowed. I am not sure why I saw issues with the colons but '.' and '-' did not cause issues when I did string replacements yesterday.

**Comment by j26151** [comment] 2022-11-19 13:33
I tested out the new build this morning. The CDP files were able to run and deploy for a few of our examples, but it failed with our ClientServer deployment. I am attaching a meld screenshot between the old way and the new way.
![image](https://user-images.githubusercontent.com/49879646/202853136-4ef5d4ec-44ad-46e8-8882-fcd7a808b74a.png)
You can see that two different "instance" elements have the same xmi:id, which is not allowed. Every xmi:id has to be unique in a given plan.  In this case, I think we could probably add "echoServer_comp" on the top entry and "EchoConnect_obj" on the bottom entry. However, without knowing much about the generation code, it would also be nice if the code could double check all IDs before placing them just in case there are situations in the future that we can't predict at the moment. Maybe you could keep a set of all used xmi:ids and each time you are generating a new one, check first that its unique. If not, either we should flag it as an error, or maybe we could throw an underscore and a number? Something to allow the CDP to be valid but also not use any randomly generated UUIDs

**Comment by eposse** [comment] 2022-11-21 22:58
I've updated the generator to ensure the ids are unique. If an id has been generated before, then a suffix is added with a number. 

But I would like to understand the situation in which that id conflict arose. What were the types of those two elements? Can you share the model, or perhaps the structure (to see how they are nested in the model)?

Thanks

**Comment by j26151** [comment] 2022-11-21 23:30
The model is our ClientServer model that you should already have access to. I believe the place where it is occurring is on an interface objects for a component. Both the component and the interface object have the same ID.

**Comment by eposse** [comment] 2022-11-21 23:45
Is this the model? [https://github.com/ZeligsoftDev/cx-reproducers/tree/main/bug/416](https://github.com/ZeligsoftDev/cx-reproducers/tree/main/bug/416)

**Comment by j26151** [comment] 2022-11-22 13:51
Thats a modified version of our ClientServer model. It should be exactly the same besides some extra references to our other example, BasicPubSub. I was fairly sure your team had access to all of our examples though. @ysroh Do you have them? Or should we add them again in another reproducer?

**Comment by ysroh** [comment] 2022-11-22 14:26
@j26151 We should have the model. I will find it for Ernesto.

**Comment by j26151** [comment] 2022-11-22 17:54
I am still seeing the same bug with duplicate IDs with the most recent build.

One last thing once the duplicate ID bug is fixed. The top level ID is a UUID, which is fine and I don't really have an issue with that. However, at the very least, we really would prefer that it not be random. If the ID could be the name of deployment plan, that would probably work for us (with the unallowed characters sanitized), however, if you instead just hashed the file contents to make the ID, that would work too. The use case here is Pull requests of deployment plans generated from the model. If nothing actually changed, we don't want it to show up in a PR. Everything in this feature already implemented by you helps us towards this goal. The last thing would be the random UUID for the plan itself.

**Comment by eposse** [comment] 2022-11-22 23:52
Ok, I think these commits address both the duplicate ids and the top-level id. Let me know if you find any more issues.

**Comment by j26151** [comment] 2022-11-28 15:32
It looks like a bug has been introduced with the Servant artifact path for our CORBA4CCM ports. With the same ClientServer example, the following is produced:
![image](https://user-images.githubusercontent.com/49879646/204317011-6b1370aa-81b5-4aae-a042-b60767893201.png)
The value needs to be SNA_Examples_EchoConnect_obj_cc and not SNA_Examples_EchoConnect_obj__cc (Note the doublt underscores before 'cc' in the bad version)  This string is used verbatim to find shared objects to dynamically load.  My guess is that this line caused the issue: https://github.com/ZeligsoftDev/CX4CBDDS/pull/438/files#diff-12192f67456ba0001e9a74e966ac8c830981c79aa18085852e6cefdafc502f59R1326  but I could be wrong.

**Comment by eposse** [comment] 2022-11-28 18:07
Sorry bout that. I wasn't aware that the string was needed literally. I pushed a fix to that. The 'cc' is now preceded by only one underscore. You can get the build [here](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/3567155075).

**Comment by j26151** [comment] 2022-11-28 20:37
This looks good to me. I tested with various examples and they all deploy after the most recent change.

In addition to merging this PR to master, we would like to discuss this change being pushed to the most recent version that we released, I believe 2.2.0? @J17359 Thoughts for how you want to handle this?

**Comment by J17359** [comment] 2022-11-29 11:02
> This looks good to me. I tested with various examples and they all deploy after the most recent change.
> 
> In addition to merging this PR to master, we would like to discuss this change being pushed to the most recent version that we released, I believe 2.2.0? @J17359 Thoughts for how you want to handle this?

@j26151 That's up to Zeligsoft I believe, not NGC. 

Sure, Zeligsoft could just push these code changes to https://github.com/ZeligsoftDev/CX4CBDDS/tree/streams/v2.2.x-maintenance but software versioning guidance generally doesn't allow new features on patch versions like that. I reckon if they don't mind that would be the easiest solution, but SNA 2.2.0 is yet to be formally released meaning we'll get this change if we just bump our dependency to Zeligsoft 2.3.0 and having Zeligsoft make another formal minor release off the `papyrus` branch.

**Comment by j26151** [comment] 2022-11-29 12:42
@eposse  I think we are all set for you to merge this to the papyrus branch. We are planning to request a 2.2.0 formal release in a different issue.

**Comment by eposse** [comment] 2022-11-29 15:20
Closing. Thanks.

**Closed by eposse** 2022-11-29 15:20 UTC
Labels: enhancement, NGC: Approved To Work
