### ISSUE TITLE
PSDD Example cannot have IDL generated by CX Extensions plugin

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#347] opened 2021-11-15 13:28 UTC
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
The PSDD example can be validated and generate IDL manually, however, the automatic tooling to do batch validations and generations fail on the model with the following message:
`Value 'org.eclipse.uml2.uml.internal.impl.ClassImpl@63aeac6d (name: PSDD_Listen, visibility: <unset>) (isLeaf: false, isAbstract: false, isFinalSpecialization: false) (isActive: false)' is not legal. (file:/home/user/workspace-papyrus/SNA_Core/PSDDPubSub/ModelFiles/PSDDPubSub.uml, -1, -1)`

**Comment by ysroh** [comment] 2021-11-16 16:10
Can you please provide some details on how to reproduce this problem? Are you referring to the CodgenUtil.validate() call?

**Comment by j26151** [comment] 2021-11-16 16:30
In our java code, we access:

   // Reference to the Zeligsoft CX utilities object
   private static final CodeGenUtil CX = CodeGenUtil.INSTANCE;

Then we use that CX object to validate a model:

     IStatus returnedStatus = CX.validateModel(GenerateUtils.convertToURI(model));

The returned status above has the error message that we posted above.

**Comment by ysroh** [comment] 2021-11-17 15:47
I am trying to reproduce this problem and I just need to verify one more thing. Is your automatic tooling invoked from a headless environment? I cannot reproduce this when I validate the BasicPubSub_PSDD example so I was wondering if this is related to the headless operation. If not, is it possible that I can take a look at your model?

**Comment by ysroh** [comment] 2021-11-17 15:48
I called validation using CodegenUtil.validate and the returned status was Status.OK.

**Comment by j26151** [comment] 2021-11-17 19:17
Sorry, I was confused myself writing this ticket. It appears its only an issue when generating IDL using the CodegenUtil API
I have uploaded the most current version of our PSDDPubSub project.

[PSDDPubSub.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/7557389/PSDDPubSub.zip)
.

**Comment by ysroh** [comment] 2021-11-17 21:24
I see. Thanks for the clarification. I will try to reproduce it.

**Comment by ysroh** [comment] 2021-11-18 15:57
I reproduced the problem and working on a fix.

**Comment by ysroh** [comment] 2021-11-18 21:22
The model must be corrupted at some point while we were fixing the PSDD library. The problem was fixed once I repaired module instantiation. The PSDD_Listen had an interface realization with duplicate values for the client property. We were not able to catch this validation since Papyrus loaded this model ignoring the extra value. The problem only occurs when loading this resource using the vanilla UML resource set. I was not able to reproduce the steps to recreate this corrupt model either. If you could provide us with steps to recreate this corrupt model then we could perhaps prevent it from happing.

**Comment by j26151** [comment] 2021-11-19 11:33
We didn't do anything specific to make that model corrupted. If it is corrupted, shouldn't it be caught by something in papyrus? Either papyrus should recognize it as corrupted or it should fail to validate. If neither of those things occur and it generates IDL/Descriptors through manual  means, there is a low chance of us catching any issues.

**Comment by ysroh** [comment] 2021-11-19 15:30
I understand your concern. Although this problem shouldn’t really happen using the stable version I can see that when it happens users may not know what the problem is. The best way to fix this problem is by preventing it but that’s not possible since we cannot reproduce it. I initially thought that this might have happened because of copy/paste but wasn't successful in reproducing it.  I can try to investigate how Papyrus ignores the duplicate value in the model and we can do the same in the Codegen util. Or we could try to load the UML file after each validation and let users know that there is a problem in the model
although I am not sure if we have a way to fix the problem automatically. I will investigate it and will let you know what would be the best option to handle this issue.

**Comment by j26151** [comment] 2021-11-19 16:03
Thank you for looking into this further. I think at a minimum we just want a way to inform users that the model is in fact corrupted. I do not think we want it to be fixed automatically without prompting the users because we want users to be in control of things changing in their workspaces.

**Comment by elder4p** [comment] 2021-11-19 17:24
@j26151 : I've just talked through this with @ysroh, and this is what we see happening:
* the model in question has a logical corruption. In a field that logically contains a set of distinct interfaces, we are seeing the same interface appearing twice.
* When Papyrus loads the model, it auto-corrects this, but does not dirty the model. However, any subsequent change to the model results in a logically correct model being saved. This presents a simple way to repair any affected model.
* The above makes it impossible for the model validator to discover the logical inconsistency, as the inconsistency is removed prior to the validator running.
* In our testing, we could not introduce the logical corruption using the Papyrus UI. Thus, we believe it was introduced by our code. Our best guess is that it arose from copy/paste before we completed the changes related to that.
* It would be difficult to determine exactly what corrupted the model. One could look at the GIT history or 'blame' of the model, and find the commit that introduced the change. You could then discuss the change with the developer who made it, and perhaps be lucky enough to understand what actions they performed to make the change. If doing such an undertaking, you are looking for an XML element with `name` attribute value `PSDD_Listen` and with a `client` attribute value that includes the same value twice, separated by a space (e.g `client="asdfasdfasdf asdfasdfasdf"`). **Caution**: those values are long, arbitrary strings that are hard to compare visually. However, the 'correct' attribute will have only a single value for the `client` attribute. Looking for a space might be the most effective way to proceed.
* We need to investigate the differences between how Papyrus loads a model and how the CX extensions plug-in loads a model. Perhaps it will be easy for use to load identically to Papyrus. @ysroh is looking at this now.

**Comment by j26151** [comment] 2021-11-22 15:15
@elder4p @ysroh Thank you for the information above. I don't think that copying and pasting was what caused this issue as we never really tested copy/paste with the PSDDPubSub model, but who knows.
In any case, I decided to investigate exactly what corrupted the model using your tips above. In our most current version of the PSDDPubSub model I was able to find the line where there was a situation with multiple client values like you mentioned above. Using git blame, I saw that I was the one that committed this corrupted model only a few days ago. This led me to finding a reproducer.

2 weeks ago we had to fix the PSDD model library in issue [[338].](https://github.com/ZeligsoftDev/CX4CBDDS/issues/338)  Once you fixed the model library, I took our PSDDPubSub model that was failing to validate and ran " Repair all Module Instantiations", validated, and committed the model. It appears that repairing all module instantiation is what caused the client attribute to have 2 values. Its completely possible that our PSDDPubSub model was corrupted in some other way as well causing this to occur, but, the version of our PSDDPubSub before the repair does not have any client attributes with 2 values whereas we can reliably corrupt the model by repairing the module instantiations.

I am attaching our PSDDPubSub model from before we ran the repair on it. You will notice that you can bring this model into your workspace, run the repair all module instantiations on it, and see that this causes the client attribute for PSDD_Listen to have the two values.

[PSDDPubSub_NeedsModuleRepair.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/7582202/PSDDPubSub_NeedsModuleRepair.zip)

**Comment by elder4p** [comment] 2021-11-22 15:41
@j26151 : Impressive detective work! We will have a look at that repair code.

**Comment by ysroh** [comment] 2021-11-29 17:42
Fixed repair module instantiation action to prevent model corruption.

**Comment by ysroh** [comment] 2021-12-01 21:01
This fix is merged to the papyrus branch and can be closed once verified.

**Comment by j26151** [comment] 2021-12-02 17:36
I have verified this fix on our end. Thank you.

**Comment by ysroh** [comment] 2021-12-02 18:01
Thanks

**Closed by ysroh** 2021-12-02 18:01 UTC
Labels: bug, Priority: Major, NGC: Approved To Work
